[project]
name = "parole-tui"
version = "1.0.1"
description = "Parole is a TUI tool to display lyrics from the song you are currently playing !"
readme = "README.md"
license = "GPL-3.0-only"
authors = [
    { name = "skueee", email = "skueee@outlook.com" }
]
keywords = ["lyrics", "music", "tui", "lrclib"]
requires-python = ">=3.14"
dependencies = [
    "dbus-next>=0.2.3 ; sys_platform == 'linux'",
    "httpx>=0.28.1",
    "textual>=8.2.8",
    "winsdk>=1.0.0b10 ; sys_platform == 'win32'",
]

[project.urls]
Repository = "https://github.com/skueee/parole.git"
Issues = "https://github.com/skueee/parole/issues"

[project.scripts]
parole = "parole_tui:main"

[tool.uvs.scripts]
format = "uv run ruff format"
lint = "uv run ruff check"
fix = "uv run ruff check --fix"
deps_check = "deptry ."
checks = ["fix", "format", "lint", "deps_check"]

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "deptry>=0.25.1",
    "ruff>=0.16.8",
    "textual-dev>=1.8.0",
    "uv-script>=0.1.9",
]

[tool.uv.build]
packages = ["src/parole_tui"]
